server:
  port: ${APP_PORT:8080}
  authentication:
    username: ${SUPERADMIN_USERNAME}
    password: ${SUPERADMIN_PASSWORD}

spring:
  application:
    name: nempotrack

  # Database Connection
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}